//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.17 at 05:30:03 PM CET 
//


package net.ivoa.xml.uws.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             A short summary of an error - a fuller representation of the
 *             error may be retrieved from /(jobs)/(jobid)/error
 *          
 * 
 * <p>Java class for ErrorSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ErrorSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{http://www.ivoa.net/xml/UWS/v1.0}ErrorType" />
 *       &lt;attribute name="hasDetail" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ErrorSummary", namespace = "http://www.ivoa.net/xml/UWS/v1.0", propOrder = {
    "message"
})
public class ErrorSummary {

    @XmlElement(namespace = "http://www.ivoa.net/xml/UWS/v1.0", required = true)
    protected String message;
    @XmlAttribute(required = true)
    protected ErrorType type;
    @XmlAttribute(required = true)
    protected boolean hasDetail;

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorType }
     *     
     */
    public ErrorType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorType }
     *     
     */
    public void setType(ErrorType value) {
        this.type = value;
    }

    /**
     * Gets the value of the hasDetail property.
     * 
     */
    public boolean isHasDetail() {
        return hasDetail;
    }

    /**
     * Sets the value of the hasDetail property.
     * 
     */
    public void setHasDetail(boolean value) {
        this.hasDetail = value;
    }

}
