//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.17 at 05:30:03 PM CET 
//


package net.ivoa.xml.uws.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExecutionPhase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExecutionPhase">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PENDING"/>
 *     &lt;enumeration value="QUEUED"/>
 *     &lt;enumeration value="EXECUTING"/>
 *     &lt;enumeration value="COMPLETED"/>
 *     &lt;enumeration value="ERROR"/>
 *     &lt;enumeration value="UNKNOWN"/>
 *     &lt;enumeration value="HELD"/>
 *     &lt;enumeration value="SUSPENDED"/>
 *     &lt;enumeration value="ABORTED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExecutionPhase", namespace = "http://www.ivoa.net/xml/UWS/v1.0")
@XmlEnum
public enum ExecutionPhase {


    /**
     *  The first phase a job is entered into
     *                   - this is where a job is being set up but no request
     *                   to run has occurred.
     * 
     */
    PENDING,

    /**
     *  An job has been accepted for execution
     *                   but is waiting in a queue
     * 
     */
    QUEUED,

    /**
     * An job is running
     * 
     */
    EXECUTING,

    /**
     *  An job has completed successfully
     *                
     * 
     */
    COMPLETED,

    /**
     *  Some form of error has occurred
     *                
     * 
     */
    ERROR,

    /**
     *  The job is in an unknown state.
     *                
     * 
     */
    UNKNOWN,

    /**
     *  The job is HELD pending execution and
     *                   will not automatically be executed - can occur after a PHASE=RUN request has been made (cf PENDING).
     *                
     * 
     */
    HELD,

    /**
     *  The job has been suspended by the
     *                   system during execution
     * 
     */
    SUSPENDED,

    /**
     *  The job has been aborted, either by
     *                   user request or by the server because of lack or
     *                   overuse of resources.
     * 
     */
    ABORTED;

    public String value() {
        return name();
    }

    public static ExecutionPhase fromValue(String v) {
        return valueOf(v);
    }

}
