//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.17 at 05:30:03 PM CET 
//


package net.ivoa.xml.uws.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.ivoa.xml.uws.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Job_QNAME = new QName("http://www.ivoa.net/xml/UWS/v1.0", "job");
    private final static QName _JobSummaryQuote_QNAME = new QName("http://www.ivoa.net/xml/UWS/v1.0", "quote");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.ivoa.xml.uws.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Jobs }
     * 
     */
    public Jobs createJobs() {
        return new Jobs();
    }

    /**
     * Create an instance of {@link ShortJobDescription }
     * 
     */
    public ShortJobDescription createShortJobDescription() {
        return new ShortJobDescription();
    }

    /**
     * Create an instance of {@link JobSummary }
     * 
     */
    public JobSummary createJobSummary() {
        return new JobSummary();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link ErrorSummary }
     * 
     */
    public ErrorSummary createErrorSummary() {
        return new ErrorSummary();
    }

    /**
     * Create an instance of {@link ResultReference }
     * 
     */
    public ResultReference createResultReference() {
        return new ResultReference();
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link JobSummary.JobInfo }
     * 
     */
    public JobSummary.JobInfo createJobSummaryJobInfo() {
        return new JobSummary.JobInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/UWS/v1.0", name = "job")
    public JAXBElement<JobSummary> createJob(JobSummary value) {
        return new JAXBElement<JobSummary>(_Job_QNAME, JobSummary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/UWS/v1.0", name = "quote", scope = JobSummary.class)
    public JAXBElement<XMLGregorianCalendar> createJobSummaryQuote(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_JobSummaryQuote_QNAME, XMLGregorianCalendar.class, JobSummary.class, value);
    }

}
