/**
 * *****************************************************************************
 * JMMC project ( http://www.jmmc.fr ) - Copyright (C) CNRS.
 *****************************************************************************
 */
package fr.jmmc.oimaging.gui;

import fr.jmmc.jmcs.gui.action.ActionRegistrar;
import fr.jmmc.oimaging.gui.action.ContinueAction;

/**
 *
 */
public class ToolBarPanel extends javax.swing.JPanel {

    /**
     * Creates new form ToolBarPanel
     */
    public ToolBarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButtonContinue = new javax.swing.JButton();
        jButtonChangeParams = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Tool bar"));
        setLayout(new java.awt.GridBagLayout());

        jButtonContinue.setAction(ActionRegistrar.getInstance().get(ContinueAction.CLASS_NAME, ContinueAction.ACTION_NAME));
        jButtonContinue.setText("Continue");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        add(jButtonContinue, gridBagConstraints);

        jButtonChangeParams.setText("Change parameters");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        add(jButtonChangeParams, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChangeParams;
    private javax.swing.JButton jButtonContinue;
    // End of variables declaration//GEN-END:variables
}
