name: CI

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Build (Maven)
        run: |
          java -version
          echo "1. Get modules"
          ./get_modules.sh
          echo "2. Build"
          ./build_gui.sh
          echo "That's All, folks !"

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: OImaging-build
          path: target/oimaging-TRUNK-jar-with-dependencies.jar

